### PR TITLE
Migrate to versions catalog

### LINKED ISSUE #155: Migrate to version catalogs (gradle)

### PR DESCRIPTION
**Pull request by indyfromoz**
This PR updates the project setup to add a dependency versions catalog and update the configuration based on the new catalog. I have split the changes to three separate commits to aid with the code review.

Some notes - 

1. I have tried my best to use `bundles` but in the Gradle files but there are no major benefits as bundles could include only 1 or 2 dependencies.
2. I had to bump up the `jvmargs` as the compiler was throwing a out of memory exception. Happy to revert the changes if it is not acceptable.
3. I have updated some of the dependencies to their latest versions and removed some duplicates. 
4. We could convert the Groovy-based `build.gradle` files into Kotlin script in the future. 

I have compiled the app with `Android Studio Dolphin | 2021.3.1.Patch1` and tested on a Pixel 6/Android 12 device. 

Could you please review the changes?

Closes #155

### CODE REVIEW

**Comment by kasem-sm** [comment]
Hey @indyfromoz, I see that you did a great job of cleaning up the `buildSrc` mess. I also learnt about the bundles section in toml file from this PR. Looks good to me atm. Just one suggestion, can you please completely get rid of the buildSrc folder and [App.kt](https://github.com/indyfromoz/SlimeKT/blob/feat/issue-155-migrate-to-toml/buildSrc/src/main/java/App.kt) file (as it is unneeded and I guess we can either hard-code the values of appVersion, etc. or find some other way).

Thank you for your current contribution 🥇

**Comment by indyfromoz** [comment]
Hello @kasem-sm!

Thank you for reviewing my PR and really appreciate your help & comments.
I am doing a new commit with your suggested changes.

**Comment by indyfromoz** [comment]
@kasem-sm Added a new commit for the suggested change. I will investigate a way to set SDK versions in a better way. 

Kindly review the changes.

**Comment by kasem-sm** [comment]
Thank you for your contribution. ✨

**Pull request merged**
