### PR TITLE
Fix #190: Validation register

### LINKED ISSUE #190: Getting "Special characters are not allowed" while entering username with space at end in Register Screen
By clicking on the register with a username having space at the end I'm getting this message in Snackbar. I think the text is not trimmed on validation. I'm passing my opinion here that may not be correct. I'm thinking that how it would be if we auto remove the special characters (or) Spaces entered while typing by showing an info msg in Snackbar.

### PR DESCRIPTION
**Pull request by rvenky125**
Added register screen validation with supporting text. I did not think it was a good practice or not here, just wanted to try. Feel free to share your opinion. I didn't write those test cases. I'll write them again if this was merged. Thank you.

### CODE REVIEW

**Comment by kasem-sm** [comment]
I think you could simply add a new check among other checks at [LoginService.kt](https://github.com/kasem-sm/SlimeKT/blob/dev/features/authentication/domain/interactors/src/main/java/kasem/sm/authentication/domain/interactors/LoginService.kt#L60) or at [RegisterService.kt](https://github.com/kasem-sm/SlimeKT/blob/dev/features/authentication/domain/interactors/src/main/java/kasem/sm/authentication/domain/interactors/RegisterService.kt#L62)

**Comment by rvenky125** [comment]
> I think you could simply add a new check among other checks at [LoginService.kt](https://github.com/kasem-sm/SlimeKT/blob/dev/features/authentication/domain/interactors/src/main/java/kasem/sm/authentication/domain/interactors/LoginService.kt#L60) or at [RegisterService.kt](https://github.com/kasem-sm/SlimeKT/blob/dev/features/authentication/domain/interactors/src/main/java/kasem/sm/authentication/domain/interactors/RegisterService.kt#L62)

I also thought that, just wanted to try and tried. I'll commit them by doing that.

**Comment by kasem-sm** [comment]
I may close this PR as of now. Thank you and sorry 😅

**Comment by rvenky125** [comment]
No problem, I'll create another one

**Pull request closed without merging**
